query getProducts(
  $limit: Int
  $offset: Int
  $price: Int
  $price_min: Int
  $price_max: Int
  $title: String
  $categoryId: Float
) {
  products(
    limit: $limit
    offset: $offset
    price: $price
    price_min: $price_min
    price_max: $price_max
    title: $title
    categoryId: $categoryId
  ) {
    id
    title
    images
    price
  }
}
